export enum ApiPath {
    FindAll = 'findAll',
    FindById = 'find',
    FindByTimetableId = 'findByTimetableId',
    FindByLessonIds = 'findByLessonIds',
    FindByMainTaskIds = 'findByMainTaskIds',
    Add = 'add',
    Update = 'update',
    Delete = 'delete',
    Register = 'register',
    Authenticate = 'authenticate',
    Logout = 'logout',
    FindByUserId = 'findByUserId',
    FindByForumId = 'findByForumId',
    FindUsersByIds = 'findUsersByIds',
    FindUserByToken = 'findUserByToken',
    FindMajorsByIds = 'findMajorsByIds',
    FindFacultiesByIds = 'findFacultiesByIds',
    UploadMessageFile = 'upload',
    GetMessageFile = 'get',
    ModifyUserPreference = 'modifyUserPreference',
    ModifyUserAuthenticationData = 'modifyUserAuthenticationData',
}
